server.port: 9000
spring:
  datasource:
   url: jdbc:mysql://${db.middleware.host}:3306/${db.middleware.dbname}?useUnicode=true&serverTimezone=Europe/Moscow&characterEncoding=UTF-8
   username: ${db.middleware.username}
   password: ${db.middleware.password}
   driverClassName: com.mysql.jdbc.Driver
   maxActive: 2
   testOnBorrow: true
   validationQuery: SELECT 1
---
spring.profiles: local,test
db.middleware:
  host: 172.19.55.38
  dbname: middleware
  username: middleware
  password: DJA7tOz427lhOkOxHOTW